WebApplication2/Models/ApplicationDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace WebApplication2.Models
{
    public class ApplicationDbContext:DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options):base(options) { }
        public DbSet<Location> Locations { get; set; }
        public DbSet<Customer> Customers  { get; set; }
        public DbSet<Employee> Employees { get; set; }
    }
}

WebApplication2/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.Models
{
    public class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Location Location { get; set; }
    }
}

WebApplication2/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.Models
{
    public class Employee
    {
        public int Id { get; set; }

        [Display(Name="Employee Name")]
        //[Required]
        public string Name { get; set; }

        [Display(Name = "Employee Email")]
        //[Required]
        public string Email { get; set; }

        [Display(Name="Employee Mobile")]
        //[Required]
        public string Mobile { get; set; }

        [Display(Name="Employee Address")]
        //[Required]
        public string Address { get; set; }
    }
}

WebApplication2/Models/ErrorViewModel.cs
using System;

namespace WebApplication2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication2/Models/Location.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.Models
{
    public class Location
    {
        public int Id { get; set; }
        public string Place { get; set; }
        public string Details { get; set; }
    }
}

WebApplication2/Models/ViewModel/CustomerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.Models.ViewModel
{
    public class CustomerViewModel
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Location { get; set; }
    }
}

WebApplication2/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Models;
using WebApplication2.Models.ViewModel;

namespace WebApplication2.Controllers
{
    public class CustomerController : Controller
    {
        private ApplicationDbContext dbContext;
        public CustomerController(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public IActionResult Index()
        {
            List<Location> locations = dbContext.Locations.ToList();
            return View(locations);
        }

        public IActionResult CustomerList(int id)
        {
            //List<Customer> customers = dbContext.Customers.Where(e => e.Location.Id == id).ToList();

            List<CustomerViewModel> customers=(from c in
            dbContext.Customers join l in dbContext.Locations
                                                on
               c.Location.Id equals l.Id
                                                where
               c.Location.Id==id select new CustomerViewModel()
                                                {
                       Name=c.Name,
                       Email=c.Email,
                       Mobile=c.Mobile,
               
               Location=l.Place     }
                                   ).ToList();
               

            return View(customers);
        }
    }
}

WebApplication2/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class EmployeeController : Controller
    {
        private ApplicationDbContext dbContext;
        public EmployeeController(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public IActionResult Index()
        {
            List<Employee> emps = dbContext.Employees.ToList();
            return View(emps);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Employee emp)
        {
            if (ModelState.IsValid)
            {
                dbContext.Employees.Add(emp);
                dbContext.SaveChanges();
                return RedirectToAction("index");
            }
            else
            {
                return View(emp);
            }
        }
        public IActionResult Delete(int id)
        {
            var emp = dbContext.Employees.SingleOrDefault(e => e.Id == id);
            if (emp != null)
            {
                dbContext.Employees.Remove(emp);
                dbContext.SaveChanges();
                return RedirectToAction("index");
            }
            else
            {
                return RedirectToAction("index");
            }
        }

        public IActionResult Edit(int id)
        {
            var emp = dbContext.Employees.SingleOrDefault(e => e.Id == id);
            return View(emp);
        }

        [HttpPost]
        public IActionResult Edit(Employee emp)
        {
            dbContext.Employees.Update(emp);
            dbContext.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

WebApplication2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication2/Views/Customer/CustomerList.cshtml
@model IEnumerable<WebApplication2.Models.ViewModel.CustomerViewModel>
@{ 
}

@if(Model.Count() <= 0)
{
    <p class="text-center text-danger">customer was not found at this location</p>
}
else
{
<table class="table table-bordered">
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Mobile</th>
        <th>Location</th>
    </tr>

    @foreach (var cust in Model)
    {
                <tr>
                    <td>@cust.Name</td>
                    <td>@cust.Email</td>
                    <td>@cust.Mobile</td>
                    <td>@cust.Location </td>
                </tr>
    }
</table>
}

WebApplication2/Views/Customer/Index.cshtml
@model IEnumerable<WebApplication2.Models.Location>
@{
}


<table class="table table-bordered">
    <tr>
        <th>Locations</th>
        <th>Details</th>
    </tr>

    @foreach (var location in Model)
            {
                <tr>
                    <td><a asp-action="CustomerList" asp-controller="Customer" asp-route-id="@location.Id">@location.Place</a></td>
                    <td>@location.Details</td>
                </tr>
            }
</table>

WebApplication2/Views/Employee/Create.cshtml
@model WebApplication2.Models.Employee
@{
}

<div class="row">
    <div class="col-6 offset-3">
        <form asp-action="Create" asp-controller="Employee" method="post">
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name"  class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mobile"></label>
                <input asp-for="Mobile" class="form-control" />
                <span asp-validation-for="Mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </form>
    </div>
</div>

WebApplication2/Views/Employee/Edit.cshtml
@model WebApplication2.Models.Employee
@{
}

<div class="row">
    <div class="col-6 offset-3">
        <form asp-action="Edit" asp-controller="Employee" method="post">
            <div class="form-group">
                <input type="hidden" asp-for="Id" />
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Mobile"></label>
                <input asp-for="Mobile" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Address"></label>
                <input asp-for="Address" class="form-control" />
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </form>
    </div>
</div>

WebApplication2/Views/Employee/Index.cshtml
@model IEnumerable<WebApplication2.Models.Employee>
@{
}

<a asp-action="Create" asp-controller="Employee" class="btn btn-outline-danger">Create</a>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Email</th>
        <th>Mobile</th>
        <th>Address</th>
        <th>Action</th>
    </tr>

    @foreach (var emp in Model)
            {
                <tr>
                    <td>@emp.Id</td>
                    <td>@emp.Name</td> 
                    <td>@emp.Email</td>
                    <td>@emp.Mobile</td>
                    <td>@emp.Address</td>
                    <td>
                        <a asp-action="Edit" asp-controller="Employee" asp-route-id="@emp.Id" onclick="return confirm('are you sure to Edit this record')">Edit</a > || <a asp-action="Delete" asp-controller="Employee" asp-route-id="@emp.Id" onclick="return confirm('are you sure to delete this record')">Delete</a>
                    </td>
                </tr>
            }
</table>

WebApplication2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplication2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>